/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#ifndef _CEVENTHANDLERAI_CPPTESTAI_H
#define _CEVENTHANDLERAI_CPPTESTAI_H

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"

#include "circuit/Circuit.h"

namespace eventhandlerai {

/**
 * This is the main C++ entry point of this AI.
 * 
 * @original_author	Robin Vobruba <hoijui.quaero@gmail.com>
 */
class CEventHandlerAI {

private:
	springai::OOAICallback* callback;
	int skirmishAIId;
	circuit::CCircuit* circuit;

public:
	CEventHandlerAI(springai::OOAICallback* callback);
	~CEventHandlerAI();

	int HandleEvent(int topic, const void* data);
}; // class CEventHandlerAI

} // namespace eventhandlerai

#endif // _CEVENTHANDLERAI_CPPTESTAI_H
