/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "EventHandlerAI.h"
#include "circuit/utils.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "WrappUnit.h"
#include "Log.h"

namespace eventhandlerai {

using namespace circuit;

CEventHandlerAI::CEventHandlerAI(springai::OOAICallback* callback) :
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1)
{
	circuit = new CCircuit(callback);
}

CEventHandlerAI::~CEventHandlerAI()
{
	delete circuit;
}

int CEventHandlerAI::HandleEvent(int topic, const void* data)
{
	int ret = ERROR_UNKNOWN;

	switch (topic) {
		case EVENT_INIT: {
			struct SInitEvent* evt = (struct SInitEvent*)data;
			ret = circuit->Init(evt->skirmishAIId, evt->callback);
			break;
		}
		case EVENT_RELEASE: {
			struct SReleaseEvent* evt = (struct SReleaseEvent*)data;
			ret = circuit->Release(evt->reason);
			break;
		}
		case EVENT_UPDATE: {
			struct SUpdateEvent* evt = (struct SUpdateEvent*)data;
			ret = circuit->Update(evt->frame);
			break;
		}
		case EVENT_MESSAGE: {
			struct SMessageEvent* evt = (struct SMessageEvent*)data;
			ret = circuit->Message(evt->player, evt->message);;
			break;
		}
		case EVENT_UNIT_CREATED: {
			struct SUnitCreatedEvent* evt = (struct SUnitCreatedEvent*)data;
			springai::Unit* unit = springai::WrappUnit::GetInstance(skirmishAIId, evt->unit);
			springai::Unit* builder = (evt->builder < 0) ? nullptr : springai::WrappUnit::GetInstance(skirmishAIId, evt->builder);
			ret = circuit->UnitCreated(unit, builder);
			break;
		}
		case EVENT_UNIT_FINISHED: {
			struct SUnitFinishedEvent* evt = (struct SUnitFinishedEvent*)data;
			ret = circuit->UnitFinished(evt->unit);
			break;
		}
		case EVENT_LUA_MESSAGE: {
			struct SLuaMessageEvent* evt = (struct SLuaMessageEvent*)data;
			ret = circuit->LuaMessage(evt->inData);
			break;
		}
		default: {
			std::string msgText = std::string("<CircuitAI> warning topic: ") + utils::int_to_string(topic);
			callback->GetLog()->DoLog(msgText.c_str());
			ret = 0;
			break;
		}
	}

	return ret;
}

} // namespace eventhandlerai
